[package]
name = "ak-py"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_atomic_kernels"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }
numpy = { version="0.27" }
bevy = { version = "0.18", default-features = false }
ak-core = { path = "../ak-core" }
ak-vis = { path = "../ak-vis" }
