[workspace]
authors = ["Mads-Peter <machri@phys.au.dk>"]
channels = ["conda-forge"]
name = "atomic-kernels"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12"

[feature.py.dependencies]
python = "3.12.*"
maturin = "*"
pip = "*"
pytest = "*"

[feature.docs.dependencies]
python = "3.13.*"
zensical = "*"
mkdocstrings-python = "*"

[feature.widget.pypi-dependencies]
ak-widget = { path = "packages/ak-widget", editable = true }

[feature.viewer.pypi-dependencies]
ak-viewer = { path = "packages/ak-viewer", editable = true }

[feature.api.pypi-dependencies]
atomic-kernels = { path = "packages/atomic-kernels", editable = true }

[environments]
default = ["py"]
docs = ["docs"]
widget = ["widget"]
viewer = ["viewer", "py"]
api = ["api", "py", "viewer"]

[tasks.test]
cmd = "pytest packages/ak-viewer/tests -m 'not viewer_integration'"
default-environment = "viewer"

[tasks.build-python]
cmd = "maturin develop --release"
cwd = "packages/ak-viewer"
default-environment = "viewer"

[tasks.build-python-nl]
cmd = "maturin develop --release"
cwd = "packages/ak-neighborlist"
default-environment = "viewer"

[tasks.neighborlist-benchmark-correctness]
depends-on = ["build-python-nl"]
cmd = "python -m benchmarks --mode correctness --profile quick"
cwd = "packages/ak-neighborlist"
default-environment = "viewer"

[tasks.neighborlist-benchmark]
depends-on = ["build-python-nl"]
cmd = "python -m benchmarks --mode timing --profile quick"
cwd = "packages/ak-neighborlist"
default-environment = "viewer"

[tasks.neighborlist-benchmark-full]
depends-on = ["build-python-nl"]
cmd = "python -m benchmarks --mode timing --profile full"
cwd = "packages/ak-neighborlist"
default-environment = "viewer"


[tasks.viewer-test-python]
cmd = "pytest packages/ak-viewer/tests/test_viewer_integration.py -m viewer_integration"
default-environment = "viewer"

[tasks.headless-test-python]
cmd = "pytest packages/ak-viewer/tests/test_headless_render.py -m viewer_integration"
default-environment = "viewer"

[tasks.rustdoc]
cmd = "cargo doc --no-deps -p ak-core -p ak-vis"

[tasks.docs-build]
depends-on = ["rustdoc"]
cmd = "zensical build --config-file docs/zensical.toml"
default-environment = "docs"

[tasks.docs-serve]
depends-on = ["rustdoc"]
cmd = "zensical serve --config-file docs/zensical.toml -o"
default-environment = "docs"

[tasks.build-wasm]
cmd = "wasm-pack build crates/ak-wasm --target web"

[tasks]
