import numpy as np
from numpy.typing import NDArray


class LightingConfig:
    ambient_brightness: float
    key_illuminance: float
    fill_illuminance: float
    back_illuminance: float
    camera_illuminance: float
    enable_fog: bool
    def __init__(
        self,
        ambient_brightness: float = 100.0,
        key_illuminance: float = 5000.0,
        fill_illuminance: float = 1000.0,
        back_illuminance: float = 800.0,
        camera_illuminance: float = 2000.0,
        enable_fog: bool = False,
    ) -> None: ...


class ColorConfig:
    @property
    def background(self) -> tuple[float, float, float]: ...
    @background.setter
    def background(self, value: tuple[float, float, float]) -> None: ...
    @property
    def cell_color(self) -> tuple[float, float, float]: ...
    @cell_color.setter
    def cell_color(self, value: tuple[float, float, float]) -> None: ...
    def __init__(
        self,
        background: tuple[float, float, float] = (0.98, 0.98, 0.98),
        cell_color: tuple[float, float, float] = (0.0, 0.0, 0.0),
    ) -> None: ...


class RenderConfig:
    show_cell: bool
    show_axes: bool
    show_ui: bool
    supercell_repeat_a: int
    supercell_repeat_b: int
    supercell_repeat_c: int
    ghost_repeated_images: bool
    ico_subdiv: int
    show_orientation_widget: bool
    orientation_widget_size_px: int
    orientation_widget_margin_px: int
    orientation_widget_offset_x_px: int
    orientation_widget_offset_y_px: int
    orientation_widget_camera_scale: float
    def __init__(
        self,
        show_cell: bool = True,
        show_axes: bool = True,
        show_ui: bool = False,
        supercell_repeat_a: int = 0,
        supercell_repeat_b: int = 0,
        supercell_repeat_c: int = 0,
        ghost_repeated_images: bool = True,
        ico_subdiv: int = 4,
        show_orientation_widget: bool = True,
        orientation_widget_size_px: int = 100,
        orientation_widget_margin_px: int = 0,
        orientation_widget_offset_x_px: int | None = None,
        orientation_widget_offset_y_px: int | None = None,
        orientation_widget_camera_scale: float = 0.065,
    ) -> None: ...


class QualityPreset:
    name: str
    ico_subdiv: int
    def __init__(self, name: str, ico_subdiv: int) -> None: ...
    @classmethod
    def from_name(cls, name: str) -> "QualityPreset": ...
    @classmethod
    def low(cls) -> "QualityPreset": ...
    @classmethod
    def medium(cls) -> "QualityPreset": ...
    @classmethod
    def high(cls) -> "QualityPreset": ...
    @classmethod
    def very_high(cls) -> "QualityPreset": ...
    def apply_to_render(self, config: "RenderConfig | None" = None) -> "RenderConfig": ...
    def apply_to_viewer(self, config: "ViewerConfig | None" = None) -> "ViewerConfig": ...


class ViewerConfig:
    @property
    def color(self) -> ColorConfig: ...
    @color.setter
    def color(self, value: ColorConfig) -> None: ...
    @property
    def lighting(self) -> LightingConfig: ...
    @lighting.setter
    def lighting(self, value: LightingConfig) -> None: ...
    @property
    def render(self) -> RenderConfig: ...
    @render.setter
    def render(self, value: RenderConfig) -> None: ...
    @property
    def initial_frame(self) -> int: ...
    @initial_frame.setter
    def initial_frame(self, value: int) -> None: ...
    @property
    def window_width(self) -> int | None: ...
    @window_width.setter
    def window_width(self, value: int | None) -> None: ...
    @property
    def window_height(self) -> int | None: ...
    @window_height.setter
    def window_height(self, value: int | None) -> None: ...
    def __init__(
        self,
        color: ColorConfig | None = None,
        lighting: LightingConfig | None = None,
        render: RenderConfig | None = None,
        initial_frame: int = 0,
        window_width: int | None = None,
        window_height: int | None = None,
    ) -> None: ...


class ViewerSession:
    def append_frame(self, frame: object) -> None: ...
    def set_frame(self, index: int) -> None: ...
    def follow_tail(self, enabled: bool = True) -> None: ...
    def set_atom_scalars(
        self, name: str, values: list[float], frame_index: int | None = None
    ) -> None: ...
    def color_by_scalar(
        self,
        name: str,
        palette: str = "viridis",
        colors: object | None = None,
        min: float | None = None,
        max: float | None = None,
        append: bool = False,
    ) -> None: ...
    def reset_atom_colors(self) -> None: ...
    def set_bonds(
        self, bonds: list[tuple[int, int]], frame_index: int | None = None
    ) -> None: ...
    def set_ball_and_stick_style(
        self,
        selection: list[bool],
        atom_scale: float = 0.45,
        bond_radius: float = 0.08,
        bond_color: tuple[float, float, float, float] = (0.7, 0.7, 0.7, 1.0),
        bond_scope: str = "both_selected",
        frame_index: int | None = None,
        append: bool = False,
    ) -> None: ...
    def reset_render_style(self) -> None: ...
    def selected_atoms(self, frame_index: int | None = None) -> list[int]: ...
    def selected_images(
        self, frame_index: int | None = None
    ) -> list[tuple[int, tuple[int, int, int]]]: ...
    def set_selection(
        self, selection: list[bool], frame_index: int | None = None
    ) -> None: ...
    def add_selection(
        self, selection: list[bool], frame_index: int | None = None
    ) -> None: ...
    def remove_selection(
        self, selection: list[bool], frame_index: int | None = None
    ) -> None: ...
    def clear_selection(self, frame_index: int | None = None) -> None: ...
    def set_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def add_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def remove_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def clear_image_selection(self, frame_index: int | None = None) -> None: ...
    def set_supercell(self, repeats: tuple[int, int, int]) -> None: ...
    def increment_supercell_axis(self, axis: int) -> None: ...
    def decrement_supercell_axis(self, axis: int) -> None: ...
    def reset_supercell(self) -> None: ...
    def set_ghost_repeated_images(self, enabled: bool = True) -> None: ...
    def toggle_ghost_repeated_images(self) -> None: ...
    def supercell(self) -> tuple[tuple[int, int, int], bool]: ...
    def set_camera_view(
        self,
        focus: tuple[float, float, float] | None = None,
        radius: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
    ) -> None: ...
    def pan_camera(self, delta: tuple[float, float, float]) -> None: ...
    def zoom_camera(
        self, factor: float | None = None, delta: float | None = None
    ) -> None: ...
    def orbit_camera(self, yaw_delta: float = 0.0, pitch_delta: float = 0.0) -> None: ...
    def frame_all(self) -> None: ...
    def start_orbit(self, yaw_rate: float = 0.5, pitch_rate: float = 0.0) -> None: ...
    def stop_camera_motion(self) -> None: ...
    def close(self) -> None: ...


class CameraController:
    def look_at(
        self,
        focus: object,
        radius: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
    ) -> None: ...
    def set_focus(self, focus: object) -> None: ...
    def set_rotation(
        self, yaw: float | None = None, pitch: float | None = None
    ) -> None: ...
    def set_radius(self, radius: float) -> None: ...
    def pan(self, delta: object) -> None: ...
    def zoom(self, factor: float | None = None, delta: float | None = None) -> None: ...
    def orbit(self, yaw_delta: float = 0.0, pitch_delta: float = 0.0) -> None: ...
    def frame_all(self) -> None: ...
    def start_orbit(self, yaw_rate: float = 0.5, pitch_rate: float = 0.0) -> None: ...
    def stop(self) -> None: ...


class ScalarRangeTracker:
    def update(self, values: object) -> tuple[float, float]: ...
    @property
    def limits(self) -> tuple[float, float]: ...


class ColorController:
    def set_atom_scalars(
        self, name: str, values: object, frame_index: int | None = None
    ) -> None: ...
    def by_scalar(
        self,
        name: str,
        palette: str = "viridis",
        colors: object | None = None,
        min: float | None = None,
        max: float | None = None,
        append: bool = False,
    ) -> None: ...
    def reset(self) -> None: ...
    def range_tracker(self) -> ScalarRangeTracker: ...


class RenderController:
    def set_bonds(self, bonds: object, frame_index: int | None = None) -> None: ...
    def set_bonds_from_adjacency(
        self, adjacency: object, frame_index: int | None = None
    ) -> None: ...
    def ball_and_stick(
        self,
        selection: object | None = None,
        atom_scale: float = 0.45,
        bond_radius: float = 0.08,
        bond_color: object = (0.7, 0.7, 0.7),
        bond_scope: str = "both_selected",
        frame_index: int | None = None,
        append: bool = False,
    ) -> None: ...
    def reset(self) -> None: ...


class ViewerSelection:
    def set_atom_scalars(
        self, name: str, values: object, frame_index: int | None = None
    ) -> ViewerSessionFacade: ...
    def color_by_scalar(
        self,
        name: str,
        values: object,
        palette: str = "viridis",
        colors: object | None = None,
        min: float | None = None,
        max: float | None = None,
        frame_index: int | None = None,
    ) -> ViewerSessionFacade: ...
    def ball_and_stick(
        self,
        atom_scale: float = 0.45,
        bond_radius: float = 0.08,
        bond_color: object = (0.7, 0.7, 0.7),
        bond_scope: str = "both_selected",
        frame_index: int | None = None,
    ) -> ViewerSessionFacade: ...


class ViewerSessionFacade:
    def append_frame(self, frame: object) -> None: ...
    def set_frame(self, index: int) -> None: ...
    def follow_tail(self, enabled: bool = True) -> None: ...
    def close(self) -> None: ...
    def selected_atoms(self, frame_index: int | None = None) -> list[int]: ...
    def selected_images(self, frame_index: int | None = None) -> list[dict]: ...
    def set_selection(self, selection: object, frame_index: int | None = None) -> None: ...
    def add_selection(self, selection: object, frame_index: int | None = None) -> None: ...
    def remove_selection(self, selection: object, frame_index: int | None = None) -> None: ...
    def clear_selection(self, frame_index: int | None = None) -> None: ...
    def set_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def add_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def remove_image_selection(
        self,
        selection: list[tuple[int, tuple[int, int, int]]],
        frame_index: int | None = None,
    ) -> None: ...
    def clear_image_selection(self, frame_index: int | None = None) -> None: ...
    def set_supercell(self, repeats: tuple[int, int, int]) -> None: ...
    def increment_supercell_axis(self, axis: int) -> None: ...
    def decrement_supercell_axis(self, axis: int) -> None: ...
    def reset_supercell(self) -> None: ...
    def set_ghost_repeated_images(self, enabled: bool = True) -> None: ...
    def toggle_supercell_distinction(self) -> None: ...
    def supercell(self) -> dict: ...
    def wait_until_ready(self, timeout: float | None = None) -> bool: ...
    def camera(self) -> CameraController: ...
    def colors(self) -> ColorController: ...
    def render(self) -> RenderController: ...
    def select(
        self, selection: object, frame_index: int | None = None
    ) -> ViewerSelection: ...


class PreparedHeadlessRenderFacade(ViewerSessionFacade):
    def save(self) -> None: ...


class PreparedViewerSession:
    @property
    def session(self) -> ViewerSession: ...
    def run(self) -> None: ...


class PreparedHeadlessRender:
    @property
    def session(self) -> ViewerSession: ...
    def save(self) -> None: ...


def distance_matrix(
    positions: NDArray[np.float64],
    numbers: NDArray[np.int32],
    cell: NDArray[np.float64],
    pbc: NDArray[np.bool_],
) -> NDArray[np.float64]: ...


def launch_viewer(trajectory: list[object], config: ViewerConfig | None = None) -> ViewerSession: ...
def prepare_viewer_session(
    trajectory: list[object], config: ViewerConfig | None = None
) -> PreparedViewerSession: ...
def prepare_render_viewer_image(
    trajectory: list[object],
    path: str,
    width: int = 800,
    height: int = 600,
    config: ViewerConfig | None = None,
) -> PreparedHeadlessRender: ...
def run_viewer_session(
    trajectory: list[object],
    callback: object,
    config: ViewerConfig | None = None,
) -> None: ...
def viewer_session(
    trajectory: list[object], config: ViewerConfig | None = None
) -> ViewerSessionFacade: ...
def headless_viewer_session(
    trajectory: list[object],
    path: str,
    width: int = 800,
    height: int = 600,
    config: ViewerConfig | None = None,
) -> PreparedHeadlessRenderFacade: ...
def trajectory_viewer(trajectory: list[object], config: ViewerConfig | None = None) -> None: ...
def viewer(structure: object, config: ViewerConfig | None = None) -> None: ...
