[package]
name = "ak-vis"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
bevy = { version = "0.18", default-features = true }
ak-core = { path = "../ak-core" }
bevy_panorbit_camera = "0.34.0"
smallvec = "1.15.1"
crossbeam-channel = "0.5"

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
